[package]
name = "ntex_task_list"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2.0", features = ["tokio"] }
ntex-files = { version = "2.0" }
serde = { version = "1.0", features = ["derive"] }
